apiVersion: v1
kind: ConfigMap
metadata:
  name: robots-configmap
data:
{{- if .Values.robotscm }}
  {{- toYaml .Values.robotscm | nindent 2 }}
{{- else }}
  robots.txt: |
    User-agent: *
{{- end }}
