{{- if .Values.scMessengerStaging.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: sc-messenger-staging
  labels:
    name: sc-messenger-staging
data:
  {{- toYaml .Values.scMessengerStaging.configMap | nindent 2 }}
{{- end }}