apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-env
  labels:
    name: laravel-env
data:
  REPEAT_JOB_CONTAINER_PORT: "{{ .Values.repeatJob.service.port }}"
  REPEAT_JOB_CONTAINER_URL: "http://repeat-job.{{ .Release.Namespace }}"
  NOTI_SERVER_CONTAINER_PORT: "{{ .Values.notiServer.service.port }}"
  NOTI_SERVER_CONTAINER_URL: "http://noti-server.{{ .Release.Namespace }}"
  APP_URL: "https://{{ .Values.host }}"
  SITE_URL: "https://{{ .Values.host }}"
  PDF_PUBLIC_URL: "https://{{ .Values.host }}"
  DOMAIN: "{{ .Values.host }}"
  # Hardcoded and unchanged values here
  APP_NAME: SC
  SERVER_TYPE: salesconnection
  APP_ENV: live
  AWS_BUCKET_TMP: salesconnection-temp-files
  DATADOG_LOG: php://stdout
  IMG_UPLOAD_PATH: /var/www/uploads
  # Email what use for idk
  MAIL_MAILER: smtp
  MAIL_HOST: smtp.mailtrap.io
  MAIL_PORT: "2525"
  MAIL_USERNAME: "null"
  MAIL_PASSWORD: "null"
  MAIL_ENCRYPTION: "null"
  MAIL_FROM_ADDRESS: "null"
  MAIL_FROM_NAME: "SC"
  # Append and overwrite
  {{- toYaml .Values.scConfigMap | nindent 2 }}