{{- if .Values.queueworker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sc-worker-deployment
  labels:
    app: sc-worker
spec:
  replicas: 3
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: sc-worker
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        configmap.reloader.stakater.com/reload: "laravel-env,sc-supervisor"
        {{- if .Values.podAnnotations }}
          {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
      labels:
        app: sc-worker
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "salesconnection.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: sc-supervisor
          configMap:
            name: sc-supervisor
        - name: supervisor-entrypoint
          configMap:
            name: supervisor-entrypoint
            defaultMode: 0777
      {{- if .Values.datadog.enabled }}
        - name: apmsocketpath
          hostPath:
            path: /var/run/datadog/
      {{- end }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: sc-supervisor
              mountPath: /etc/supervisor/conf.d/
            - name: supervisor-entrypoint
              mountPath: /var/post_deploy.sh
              subPath: entrypoint.sh
          {{- if .Values.datadog.enabled }}
            - name: apmsocketpath
              mountPath: /var/run/datadog
          {{- end }}
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.image.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.image.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - name: supervisor
              containerPort: 9001
              protocol: TCP
        - name: supervisor-prometheus-exporter
          image: 672944514151.dkr.ecr.ap-southeast-1.amazonaws.com/supervisor-prometheus-exporter:latest
          ports:
            - name: metrics
              containerPort: 9876
              protocol: TCP
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.queueworker.topologySpreadConstraints}}
      {{- with .Values.queueworker.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- else }}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "topology.kubernetes.io/zone"
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: sc-worker
          matchLabelKeys:
            - pod-template-hash
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}