{{- if .Values.scMessenger.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sc-messenger-deployment
  labels:
    app: sc-messenger
spec:
  replicas: {{ .Values.scMessenger.replicaCount }}
  selector:
    matchLabels:
      app: sc-messenger
  template:
    metadata:
      annotations:
        configmap.reloader.stakater.com/reload: "sc-messenger"
        {{- if .Values.scMessenger.podAnnotations }}
          {{- toYaml .Values.scMessenger.podAnnotations | nindent 8 }}
        {{- end }}
      labels:
        app: sc-messenger
    spec:
      {{- with .Values.scMessenger.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.scMessenger.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.scMessenger.podSecurityContext | nindent 8 }}
      volumes:
      {{- if .Values.scMessenger.datadog.enabled }}
        - name: apmsocketpath
          hostPath:
            path: /var/run/datadog/
      {{- end }}
      containers:
        - name: sc-messenger
          image: "{{ .Values.scMessenger.image.repository }}:{{ .Values.scMessenger.image.tag }}"
          imagePullPolicy: {{ .Values.scMessenger.image.pullPolicy }}
          ports:
            - name: supervisor
              containerPort: 9001
              protocol: TCP
          {{- with .Values.scMessenger.image.ports }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: DD_TRACE_AGENT_URL
              value: 'unix:///var/run/datadog/apm.socket'
          {{- with .Values.scMessenger.image.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.scMessenger.image.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.scMessenger.resources | nindent 12 }}
          volumeMounts:
          {{- if .Values.scMessenger.datadog.enabled }}
            - name: apmsocketpath
              mountPath: /var/run/datadog
          {{- end }}
        - name: supervisor-prometheus-exporter
          image: 672944514151.dkr.ecr.ap-southeast-1.amazonaws.com/supervisor-prometheus-exporter:latest
          ports:
            - name: metrics
              containerPort: 9876
              protocol: TCP
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.scMessenger.topologySpreadConstraints}}
      {{- with .Values.scMessenger.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- else }}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "topology.kubernetes.io/zone"
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: sc-messenger
          matchLabelKeys:
            - pod-template-hash
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}