{{- if .Values.scMessengerStaging.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sc-messenger-staging-deployment
  labels:
    app: sc-messenger-staging
spec:
  replicas: {{ .Values.scMessengerStaging.replicaCount }}
  selector:
    matchLabels:
      app: sc-messenger-staging
  template:
    metadata:
      annotations:
        configmap.reloader.stakater.com/reload: "sc-messenger-staging"
        {{- if .Values.scMessengerStaging.podAnnotations }}
          {{- toYaml .Values.scMessengerStaging.podAnnotations | nindent 8 }}
        {{- end }}
      labels:
        app: sc-messenger-staging
    spec:
      {{- with .Values.scMessengerStaging.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.scMessenger.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.scMessengerStaging.podSecurityContext | nindent 8 }}
      volumes:
      {{- if .Values.scMessengerStaging.datadog.enabled }}
        - name: apmsocketpath
          hostPath:
            path: /var/run/datadog/
      {{- end }}
      containers:
        - name: sc-messenger-staging
          image: "{{ .Values.scMessengerStaging.image.repository }}:{{ .Values.scMessengerStaging.image.tag }}"
          imagePullPolicy: {{ .Values.scMessengerStaging.image.pullPolicy }}
          {{- with .Values.scMessengerStaging.image.ports }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: DD_TRACE_AGENT_URL
              value: 'unix:///var/run/datadog/apm.socket'
          {{- with .Values.scMessengerStaging.image.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.scMessengerStaging.image.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.scMessengerStaging.resources | nindent 12 }}
          volumeMounts:
          {{- if .Values.scMessengerStaging.datadog.enabled }}
            - name: apmsocketpath
              mountPath: /var/run/datadog
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.scMessengerStaging.topologySpreadConstraints}}
      {{- with .Values.scMessengerStaging.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- else }}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "topology.kubernetes.io/zone"
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: sc-messenger-staging
          matchLabelKeys:
            - pod-template-hash
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}