# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: extracted-secrets
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: secretstore-parameterstore
#     kind: SecretStore
#   target:
#     name: acm
#     creationPolicy: Owner
#   data:
#     - secretKey: prelive-arn
#       remoteRef:
#         metadataPolicy: Fetch
#         key: /acm/prelive2/arn