apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: sc-pod-monitor-php-fpm-prometheus-crd
spec:
  selector:
    matchLabels:
      {{- include "salesconnection.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
    - port: metrics
      interval: 2s
      scrapeTimeout: 1s
  namespaceSelector:
    matchNames:
      - salesconnection