apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: sc-pod-monitor-prometheus-crd
spec:
  selector:
    matchLabels:
      {{- include "salesconnection.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
  - port: metrics