apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: sc-pod-monitor-supervisor-prometheus-crd
spec:
  selector:
    matchLabels:
      app: sc-worker
  podMetricsEndpoints:
    - port: metrics
      interval: 2s
      scrapeTimeout: 1s
  namespaceSelector:
    matchNames:
      - salesconnection