# apiVersion: external-secrets.io/v1beta1
# kind: SecretStore
# metadata:
#   name: secretstore-parameterstore
# spec:
#   provider:
#     aws:
#       service: ParameterStore
#       region: {{ if .Values.region }}{{ .Values.region }}{{ else }}{{ "ap-southeast-1" }}{{ end }}
#       auth:
#         jwt:
#           serviceAccountRef:
#             name: external-secrets-service-account