apiVersion: v1
kind: Service
metadata:
  name: {{ include "salesconnection.fullname" . }}
  labels:
    {{- include "salesconnection.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
    - port: 9253
      targetPort: 9253
      protocol: TCP
      name: php-fpm-prometheus-exporter
    - port: 9876
      targetPort: 9876
      protocol: TCP
      name: supervisor-prometheus-exporter
  selector:
    {{- include "salesconnection.selectorLabels" . | nindent 4 }}
