# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: external-secrets-service-account
#   labels:
#     {{- include "salesconnection.labels" . | nindent 4 }}
#   annotations:
#     eks.amazonaws.com/role-arn: arn:aws:iam::672944514151:role/external-secrets-parameter-store