{{- if .Values.scMessenger.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.scMessenger.serviceAccount.name }}
  labels:
    {{- include "salesconnection.labels" . | nindent 4 }}
  {{- with .Values.scMessenger.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
