apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "srv-change-status.configMapName" . }}
  labels:
    {{- include "srv-change-status.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configMap.data | nindent 2 }}
  PORT: "{{ .Values.service.port | default 80 }}"
