apiVersion: apps/v1
kind: Deployment
metadata:
  name: br-controller
  labels:
    {{- include "batch-reminder.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "batch-reminder.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "batch-reminder.labels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "672944514151.dkr.ecr.ap-southeast-1.amazonaws.com/batch-reminder-ecr:{{ .Values.version | default .Chart.AppVersion }}"
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 3000
        envFrom:
        - secretRef:
            name: {{ include "batch-reminder.secretName" . }}
