apiVersion: apps/v1
kind: Deployment
metadata:
  name: br-controller
spec:
  selector:
    matchLabels:
      app: br-controller
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: br-controller
    spec:
      containers:
      - name: controller
        image: 672944514151.dkr.ecr.ap-southeast-1.amazonaws.com/batch-reminder-ecr:{{ .Values.version }}
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 3000
        envFrom:
        - secretRef:
            name: br-secret
