apiVersion: v1
kind: Secret
metadata:
  name: {{ include "batch-reminder.secretName" . }}
  labels:
    {{- include "batch-reminder.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.env.database_url | b64enc }}
