apiVersion: v1
kind: Service
metadata:
  name: {{ include "batch-reminder.fullname" . }}
spec:
  selector:
    {{- include "batch-reminder.labels" . | nindent 4 }}
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
