apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "messenger.configMapName" . }}
  labels:
    {{- include "messenger.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configMap.data | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "messenger.configMapSupervisordName" . }}
  labels:
    app: {{ include "messenger.configMapSupervisordName" . }}
data:
  supervisor-messenger.conf: |
    [supervisord]
    nodaemon=true

    [program:php-fpm]
    command=/usr/local/sbin/php-fpm -F
    stdout_logfile=/dev/fd/1
    stdout_logfile_maxbytes=0
    stderr_logfile=/dev/stderr
    stderr_logfile_maxbytes=0
    autostart=true
    autorestart=true

    [program:nginx]
    command=/usr/sbin/nginx -g "daemon off;"
    stdout_logfile=/dev/null
    stdout_logfile_maxbytes=0
    stderr_logfile=/dev/stderr
    stderr_logfile_maxbytes=0
    username=www-data
    autorestart=true
    autostart=true

    {{ if .Values.configMap.data.QUEUE_CONNECTION -}}
    [program:runner]
    process_name=%(program_name)s_%(process_num)02d
    command=/usr/local/bin/php /app/artisan queue:work {{ .Values.configMap.data.QUEUE_CONNECTION }} --timeout={{ .Values.supervisor.timeout }}
    autostart=true
    autorestart=true
    user=root
    numprocs={{ .Values.supervisor.numproc }}
    redirect_stderr=true
    stdout_logfile=/dev/fd/1
    stdout_logfile_maxbytes=0
    {{- end }}
