apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "caction.configMapName" . }}
  labels:
    name: {{ include "caction.configMapName" . }}
data:
  {{- toYaml .Values.configMap.data | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: robots-configmap
data:
{{- with .Values.robotsConfigMap.data }}
  {{- toYaml . | nindent 2 }}
{{- else }}
  robots.txt: |
    User-agent: *
{{- end }}
