apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "caction.configMapName" . }}
  labels:
    name: {{ include "caction.configMapName" . }}
data:
  {{- toYaml .Values.configMap.data | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "caction.fileBasedConfigMapName" . }}
data:
  {{- with .Values.configMap.files.robotsTxt }}
  robots.txt: {{- toYaml . | nindent 2 }}
  {{- else }}
  robots.txt: |
    User-agent: *
  {{- end }}
  {{- if .Values.queueJob.enabled }}
  entrypoint.sh: |
    {{- .Values.configMap.files.entrypointSh | nindent 4 }}
  supervisor
  {{- range .Values.queueJob.list }}
  {{- end }}
  {{- end }}
---
