apiVersion: v1
kind: Secret
metadata:
  name: {{ include "caction-website.secretName" . }}
  labels:
    app: {{ include "caction-website.secretName" . }}
data:
  {{- range $k, $v := .Values.secret.data }}
    {{- $k | nindent 4 }}: {{ $v | b64enc | quote }}
  {{- end }}
