apiVersion: v1
kind: Service
metadata:
  name: {{ include "caction-website.fullname" . }}
  labels:
    {{- include "caction-website.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 9000
      targetPort: fpm
      protocol: TCP
      name: fpm
    {{- with .Values.service.extraPorts }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  selector:
    {{- include "caction-website.selectorLabels" . | nindent 4 }}
