{{- if not (empty .Values.configMap.data) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "microservice.configMapName" . }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configMap.data | nindent 2 }}
{{- end }}
