{{- if and .Values.persistence.enabled (and (empty .Values.persistence.existingClaim) (not (empty .Values.persistence.storageClass))) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "microservice.fullname" . }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
  {{- with .Values.persistence.annotations }}
  annotations:
    {{- . toYaml | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.persistence.accessModes }}
  accessModes:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- with .Values.persistence.volumeName }}
  volumeName: {{ . }}
  {{- end }}
{{- end }}
