{{- if not (empty .Values.secret.data) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "microservice.secretName" . }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.secret.data }}
    {{- $k | nindent 4 }}: {{ $v | b64enc | quote }}
  {{- end }}
{{- end }}
